from pathlib import Path
import json
import os
import torch
import pathlib
import torchvision
from torch.utils.data import Dataset
from torchvision import datasets,transforms
from typing import Tuple,Dict,List
from PIL import Image
from torch import nn
from torch.utils.data import DataLoader,random_split


hidden_unit=256

DATA_DIR      = Path(__file__).parent / "data/food-101/images"
_LABELS_PATH  = Path(__file__).parent / "ingredient_labels.json"

# Per-image ingredient labels generated by build_image_labels.py
# Key: "class_name/image_stem"  Value: ["ingredient1", "ingredient2", ...]
if _LABELS_PATH.exists():
    _IMAGE_LABELS = json.loads(_LABELS_PATH.read_text())
else:
    _IMAGE_LABELS = {}
    print("[warning] ingredient_labels.json not found — run build_image_labels.py first")

# Build vocabulary from all labels
INGREDIENT_VOCAB: set = set()
for ingredients in _IMAGE_LABELS.values():
    INGREDIENT_VOCAB.update(ingredients)

INGREDIENT_VOCAB = sorted(INGREDIENT_VOCAB)
print(INGREDIENT_VOCAB)
NUM_INGREDIENTS  = len(INGREDIENT_VOCAB)
ING2IDX          = {ing: idx for idx, ing in enumerate(INGREDIENT_VOCAB)}


def _image_to_multihot(image_path: Path) -> torch.Tensor:
    label = torch.zeros(NUM_INGREDIENTS)
    key   = f"{image_path.parent.name}/{image_path.stem}"
    for ing in _IMAGE_LABELS.get(key, []):
        if ing in ING2IDX:
            label[ING2IDX[ing]] = 1.0
    return label


#find class_helper
def find_classes(directory:str)->Tuple[List[str],Dict[str,int]]:
    """Find the class folder names in a target directory"""
    class_name_found=sorted([entry.name for entry in list(os.scandir(directory))])
    
    if not class_name_found:
        raise FileNotFoundError("fuck")
    
    class_to_idx={class_name : i for i,class_name in enumerate(class_name_found)}
    
    return class_name_found,class_to_idx


simple_transform=transforms.Compose([transforms.Resize(size=(224,224)),transforms.ToTensor()])
class FoodIngredientDataset(Dataset):
    def __init__(self, targ_dir:str,split:str=None , transform=None):
        all_paths = list(pathlib.Path(targ_dir).glob("*/*.jpg"))
        if split is not None:
            meta_file = Path(targ_dir).parent / "meta" / f"{split}.txt"
            allowed   = set(meta_file.read_text().splitlines())
            all_paths = [p for p in all_paths if f"{p.parent.name}/{p.stem}" in allowed]
        # keep only images that have ingredient labels — avoids all-zero training targets
        if _IMAGE_LABELS:
            all_paths = [p for p in all_paths
                         if f"{p.parent.name}/{p.stem}" in _IMAGE_LABELS]
        self.transform = transform
        self.classes, self.class_to_idx = find_classes(targ_dir)
        self.paths = all_paths

    def load_image(self,index:int)->Image.Image:
        "open an image via a path and returns it"
        image_path=self.paths[index]
        return Image.open(image_path).convert("RGB")

    def __len__(self)->int:
        return len(self.paths)

    def __getitem__(self,index):
        img = self.load_image(index)
        label = _image_to_multihot(self.paths[index])

        if self.transform:
            return self.transform(img),label
        else:
            return img,label

# Step 4 — two-layer MLP head: 1280 → 256 → 128 → NUM_INGREDIENTS
class MultiLabelHead(nn.Module):
    def __init__(self, input_shape, hidden_unit, output_shape):
        super().__init__()
        self.classifier = nn.Sequential(
            nn.Linear(input_shape, hidden_unit),
            nn.BatchNorm1d(hidden_unit),
            nn.ReLU(),
            nn.Dropout(p=0.3),
            nn.Linear(hidden_unit, hidden_unit // 2),
            nn.BatchNorm1d(hidden_unit // 2),
            nn.ReLU(),
            nn.Dropout(p=0.2),
            nn.Linear(hidden_unit // 2, output_shape),
        )

    def forward(self, x):
        return self.classifier(x)


# Step 5 — IngredientNet: frozen EfficientNet-B0 backbone + MultiLabelHead
class IngredientNet(nn.Module):
    def __init__(self, num_ingredients):
        super().__init__()
        backbone = torchvision.models.efficientnet_b0(weights="IMAGENET1K_V1")
        # freeze every backbone parameter — only the head will be trained
        for param in backbone.parameters():
            param.requires_grad = False
        # keep spatial feature extractor + global average pool; drop the classifier
        self.backbone = nn.Sequential(backbone.features, backbone.avgpool)
        self.head = MultiLabelHead(1280, hidden_unit, num_ingredients)

    def forward(self, x):
        feat = self.backbone(x).flatten(1)  # [B, 1280]
        return self.head(feat)              # [B, num_ingredients]  (raw logits)

def precision_recall_f1(preds: torch.Tensor, targets: torch.Tensor, threshold: float = 0.5):
    binary_preds = (torch.sigmoid(preds) >= threshold).float()
    targets = targets.float()

    TP = (binary_preds * targets).sum().item()
    FP = (binary_preds * (1 - targets)).sum().item()
    FN = ((1 - binary_preds) * targets).sum().item()

    precision = TP / (TP + FP) if (TP + FP) > 0 else 0.0
    recall    = TP / (TP + FN) if (TP + FN) > 0 else 0.0
    f1        = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0.0

    return precision, recall, f1



# ---------------------------------------------------------------------------
# Transforms
# ---------------------------------------------------------------------------
train_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
])
val_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
])

# ---------------------------------------------------------------------------
# Step 7 — train / val loops
# ---------------------------------------------------------------------------
def train_one_epoch(model, dataloader, loss_fn, optimizer, device):
    from tqdm.auto import tqdm
    model.train()
    total_loss = total_f1 = 0
    for X, y in tqdm(dataloader, leave=False):
        X, y   = X.to(device), y.to(device)
        logits = model(X)
        loss   = loss_fn(logits, y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
        _, _, f1 = precision_recall_f1(logits.detach(), y.detach())
        total_f1 += f1
    n = len(dataloader)
    return total_loss / n, total_f1 / n


def val_one_epoch(model, dataloader, loss_fn, device):
    from tqdm.auto import tqdm
    model.eval()
    total_loss = total_f1 = 0
    with torch.inference_mode():
        for X, y in tqdm(dataloader, leave=False):
            X, y   = X.to(device), y.to(device)
            logits = model(X)
            total_loss += loss_fn(logits, y).item()
            _, _, f1 = precision_recall_f1(logits, y)
            total_f1 += f1
    n = len(dataloader)
    return total_loss / n, total_f1 / n


# ---------------------------------------------------------------------------
# Step 8 — inference helper
# ---------------------------------------------------------------------------
_infer_tf = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
])

def predict_ingredients(model, image_path: str, threshold: float = 0.5) -> list:
    device = next(model.parameters()).device
    img    = Image.open(image_path).convert("RGB")
    tensor = _infer_tf(img).unsqueeze(0).to(device)
    model.eval()
    with torch.inference_mode():
        logits = model(tensor)
    probs   = torch.sigmoid(logits).squeeze(0)
    indices = (probs >= threshold).nonzero(as_tuple=True)[0].tolist()
    return [INGREDIENT_VOCAB[i] for i in indices]


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    import torch.optim as optim
    from tqdm.auto import tqdm

    BATCH_SIZE  = 32
    NUM_WORKERS = 2
    EPOCHS      = 50
    PATIENCE    = 10

    device = torch.device(
        "cuda" if torch.cuda.is_available()
        else "mps"  if torch.backends.mps.is_available()
        else "cpu"
    )
    print(f"Device: {device}")

    # double-load so train and val get different transforms
    train_full = FoodIngredientDataset(DATA_DIR, split="train", transform=train_transform)
    val_full   = FoodIngredientDataset(DATA_DIR, split="train", transform=val_transform)
    val_n   = int(0.2 * len(train_full))
    train_n = len(train_full) - val_n
    indices = torch.randperm(len(train_full),
                             generator=torch.Generator().manual_seed(42)).tolist()
    train_ds = torch.utils.data.Subset(train_full, indices[val_n:])
    val_ds   = torch.utils.data.Subset(val_full,   indices[:val_n])

    train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,
                              num_workers=NUM_WORKERS, drop_last=True)
    val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE, shuffle=False,
                              num_workers=NUM_WORKERS)

    print(f"Train: {len(train_ds)} | Val: {len(val_ds)}")

    model   = IngredientNet(NUM_INGREDIENTS).to(device)
    loss_fn = nn.BCEWithLogitsLoss()
    # only head parameters are trainable — backbone is frozen
    optimizer = optim.Adam(model.head.parameters(), lr=1e-3)

    best_f1    = 0.0
    no_improve = 0
    os.makedirs("checkpoints", exist_ok=True)

    for epoch in tqdm(range(EPOCHS)):
        tr_loss, tr_f1 = train_one_epoch(model, train_loader, loss_fn, optimizer, device)
        vl_loss, vl_f1 = val_one_epoch(model, val_loader,   loss_fn, device)

        print(
            f"Epoch {epoch+1:03d} | "
            f"train_loss {tr_loss:.4f}  train_f1 {tr_f1:.4f} | "
            f"val_loss {vl_loss:.4f}  val_f1 {vl_f1:.4f}"
        )

        if vl_f1 > best_f1:
            best_f1    = vl_f1
            no_improve = 0
            torch.save(model.state_dict(), "checkpoints/ingredient_net.pt")
            print(f"  Saved checkpoint (val_f1={best_f1:.4f})")
        else:
            no_improve += 1

        if no_improve >= PATIENCE:
            print(f"Early stopping — no improvement for {PATIENCE} epochs.")
            break


